/*

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

*/

var dateStart = new Date();
var soluce;

var triangleNumber = [];
var getTriangleNumber = function(n){
  if (n === 1)
    return 1;
  else if (typeof triangleNumber[n] !== 'undefined')
    return triangleNumber[n];
  else {
    triangleNumber[n] = getTriangleNumber(n-1) + n;
    return triangleNumber[n];
  }
}

var howManyDivisors = function(n) {
  if(n === 1)
    return 1;
  else{
    var divisor = 0; // 1 et n
    for (var i = 1; i < Math.sqrt(n); i++) {
      if(n%i === 0 )
        divisor += 2;
    };
    if(n%Math.round(Math.sqrt(n)) === 0)
      divisor++;
    return divisor;
  }
}

var i = 0;
do {
  i++
}
while(howManyDivisors(getTriangleNumber(i)) <= 500)

soluce = getTriangleNumber(i);

var dateEnd = new Date();

console.log(soluce, (dateEnd-dateStart)/1000 + 's');
